# Generated by Django 4.2.5 on 2023-10-31 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_active_on_main',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Активность на главной странице'),
        ),
    ]
